spring:
  profiles:
#    - db
  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 10MB
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        ddl-auto: update
        default_batch_fetch_size: 30
        format_sql: true
    show-sql: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/nongsanmul?serverTimezone=UTC&characterEncoding=UTF-8
    username: nongsanmul
    password: nongsanmul



