# GOOGLE
spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 162989674152-q3p3602rsf5f78kljgv5pvki8q25lqng.apps.googleusercontent.com
            client-secret: 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
            # redirectUri : http://localhost:8080/login/oauth2/code/google
            scope:
              - profile
              - email
  app:
    auth:
      tokenSecret: xCVZNxF0iX
      tokenExpirationMsec: 3600
    oauth2:
      authorizedRedirectUris:
        - http://localhost:8080/oauth2/redirect

